spring:
  application:
    name: ims-service
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://192.168.3.102:10002/ims}
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
    initialization-mode: always
    sql-script-encoding: UTF-8
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8081/eureka}
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true